services:
  web:
    image: python:3.12-slim
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r app/requirements.txt &&
        pip install "fastapi[standard]" &&
        fastapi run --workers 4 app/main.py"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
