[project]
name = "chattychatty"
version = "0.0.1"

authors = [{ name = "Min Soe Zan" }]

# readme = { file = "README.md", content-type = "text/markdown" }

[project.urls]
Repository = "https://github.com/minsoe/ChattyChatty.git"

[tool.ruff]
target-version = "py311"

line-length = 88
preview = false

[tool.ruff.lint]
select = ["E", "F", "I", "FA"]
# `E` for Pycodestyle errors
# `F` for Pyflakes errors
# `I` for isort (import sorting)
# `FA` for Enforce from __future__ import annotations

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
