[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[project]

name = "chattychatty"
version = "0.0.1"

authors = [
  {name = "Min Soe Zan"}
]

readme = {file = "README.md", content-type = "text/markdown"}


requires-python = "~= 3.11.0"

dependencies = [
    "openai~=2.6.1",
    "pymongo~=4.9.1",
    "pydantic~=2.9.2",
    "python-dotenv~=1.0.1",
    "motor~=3.6.0",
    "beanie~=1.26.0",
    "fastapi~=0.120.1",
    "camel-converter~=4.0.1",
    # "pydantic-ai~=1.0.5",
    "typing_inspect~=0.9.0",
    "fastapi-utils~=0.8.0",
    "httpx~=0.27.2",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-tornasync",
    "mongomock_motor~=0.0.34",
    "fastapi[standard]"
]

[project.urls]
Repository = "https://github.com/minsoe/ChattyChatty.git"

[tool.mypy]
plugins = ['pydantic.mypy']
    
# [tool.pytest.ini_options]
# addopts = "-v --cov=your_project_name --cov-report term-missing --cov-report=html"



[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = [
    "--import-mode=importlib",
]
python_files = ["test_*.py", "*_test.py", "*_tests.py"]

# [tool.tox]
# requires = ["tox>=4.19"]
# env_list = ["3.14t", "3.14", "3.13", "3.12", "type"]

# [tool.tox.env_run_base]
# description = "Run test under {base_python}"
# commands = [["pytest"]]

# [tool.tox.env.type]
# description = "run type check on code base"
# deps = ["mypy==1.18.2", "types-cachetools>=5.5.0.20240820", "types-chardet>=5.0.4.6"]
# commands = [["mypy", "src{/}tox"], ["mypy", "tests"]]


